(function(){
"use strict";
var app=null, dbUrl="https://coldguard-fdfc5-default-rtdb.asia-southeast1.firebasedatabase.app", breaches=new Map();
var $=function(id){return document.getElementById(id);};
var esc=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]);});};
function user(){return app&&app.currentUser||(window.firebase&&window.firebase.auth?window.firebase.auth().currentUser:null);}
function db(){try{return app&&app.dbService&&app.dbService.db||window.firebase.app().database(dbUrl);}catch(e){return null;}}
function toast(msg,type){if(app&&app.modals&&app.modals.showToast)app.modals.showToast(msg,type||"info");else alert(msg);}
function field(n,l,p,t,req){return '<label class="text-xs font-semibold text-slate-700">'+l+'<input name="'+n+'" type="'+t+'" '+(t==="number"?'step="any" ':'maxlength="100" ')+(req?"required ":"")+' placeholder="'+esc(p)+'" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"></label>';}
function controls(){
 if(!app||app.currentView!=="shipments")return;
 var h=document.querySelector("#main-content-view h1"), header=h&&h.parentElement&&h.parentElement.parentElement;
 if(header){var a=$("cg-actions");if(!a){a=document.createElement("div");a.id="cg-actions";a.className="flex flex-wrap items-center gap-2";header.appendChild(a);}
 a.innerHTML='<button id="cg-test-email" class="px-3 py-2 text-xs font-semibold bg-white border border-slate-300 rounded-xl">Create test email</button><button id="cg-add" class="px-3.5 py-2 text-xs font-bold bg-emerald-600 text-white rounded-xl">+ Add shipment</button>';
 $("cg-add").onclick=addForm;$("cg-test-email").onclick=function(){send({type:"test",shipmentId:"EMAIL-TEST"});};}
 document.querySelectorAll("#shipments-table-wrapper tbody tr[data-id]").forEach(function(row){var id=row.getAttribute("data-id"),cell=row.lastElementChild;if(!id||!cell||cell.querySelector(".cg-remove"))return;var b=document.createElement("button");b.className="cg-remove ml-1 px-2.5 py-1.5 text-xs font-semibold text-red-700 bg-red-50 border border-red-200 rounded-lg";b.textContent="Remove";b.onclick=function(e){e.preventDefault();e.stopPropagation();remove(id);};cell.appendChild(b);});
}
function addForm(){
 var modal=$("modal-container"),profiles=app.vaccineProfiles||{};if(!modal)return;
 var opts=Object.keys(profiles).map(function(k){return '<option value="'+esc(k)+'">'+esc(profiles[k].categoryName||k)+'</option>';}).join("");
 modal.innerHTML='<div class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-4"><form id="cg-form" class="w-full max-w-2xl max-h-[92vh] overflow-y-auto bg-white rounded-2xl shadow-2xl p-6 space-y-4"><div class="flex justify-between"><h2 class="text-xl font-extrabold">Add new shipment</h2><button id="cg-close" type="button" class="text-2xl">&times;</button></div><div class="grid grid-cols-1 sm:grid-cols-2 gap-3">'+
 field("id","Shipment ID","CG-IN-NEW-001","text",true)+field("vaccineName","Product / vaccine","Vaccine name","text",true)+
 '<label class="text-xs font-semibold">Category<select name="vaccineCategory" class="mt-1 w-full rounded-lg border p-2.5">'+opts+'</select></label>'+
 field("batchNumber","Batch number","BATCH-001","text",true)+field("minTemp","Minimum temperature (°C)","","number",true)+field("maxTemp","Maximum temperature (°C)","","number",true)+field("currentLocation","Origin","Origin facility","text",true)+field("destinationFacility","Destination","Destination facility","text",true)+field("driverName","Driver name","Optional","text",false)+field("sensorDeviceId","Sensor / device ID","Optional","text",false)+
 '</div><p id="cg-error" class="hidden text-xs text-red-700"></p><div class="flex justify-end gap-2"><button id="cg-cancel" type="button" class="px-4 py-2 border rounded-lg">Cancel</button><button id="cg-save" type="submit" class="px-4 py-2 font-bold text-white bg-emerald-600 rounded-lg">Save shipment</button></div></form></div>';
 var f=$("cg-form"),close=function(){$("modal-container").innerHTML="";};
 $("cg-close").onclick=close;$("cg-cancel").onclick=close;
 function defaults(){var p=profiles[f.elements.vaccineCategory.value]||{};f.elements.minTemp.value=Number.isFinite(Number(p.minTemp))?p.minTemp:2;f.elements.maxTemp.value=Number.isFinite(Number(p.maxTemp))?p.maxTemp:8;}
 f.elements.vaccineCategory.onchange=defaults;defaults();
 f.onsubmit=async function(e){e.preventDefault();var err=$("cg-error"),btn=$("cg-save");err.classList.add("hidden");btn.disabled=true;btn.textContent="Saving…";
 try{var d=Object.fromEntries(new FormData(f).entries()),u=user(),database=db();d.id=d.id.trim();d.minTemp=Number(d.minTemp);d.maxTemp=Number(d.maxTemp);
 if(!/^[A-Za-z0-9_-]{1,64}$/.test(d.id))throw Error("ID may contain only letters, numbers, hyphens and underscores.");
 if(!Number.isFinite(d.minTemp)||!Number.isFinite(d.maxTemp)||d.minTemp>=d.maxTemp)throw Error("Minimum temperature must be lower than maximum temperature.");
 if(!u||u.isDemo||!u.uid||!database)throw Error("Sign in with Firebase to save shipments; demo mode cannot write to the database.");
 var ref=database.ref("shipments/"+d.id);if((await ref.once("value")).exists())throw Error("That shipment ID already exists.");
 var now=new Date().toISOString(),s={id:d.id,shipmentId:d.id,vaccineName:d.vaccineName.trim(),productName:d.vaccineName.trim(),vaccineCategory:d.vaccineCategory,batchNumber:d.batchNumber.trim(),minTemp:d.minTemp,maxTemp:d.maxTemp,minAllowedTemperature:d.minTemp,maxAllowedTemperature:d.maxTemp,currentLocation:d.currentLocation.trim(),origin:d.currentLocation.trim(),destinationFacility:d.destinationFacility.trim(),destination:d.destinationFacility.trim(),driverName:d.driverName.trim(),sensorDeviceId:d.sensorDeviceId.trim(),status:"In Transit",createdAt:now,updatedAt:now,createdByUid:u.uid,currentTemperature:(d.minTemp+d.maxTemp)/2,temperatureUnit:"C"};
 await ref.set(s);if(app.simulation&&Array.isArray(app.simulation.shipments)){app.simulation.shipments=app.simulation.shipments.filter(function(x){return String(x.id)!==d.id;});app.simulation.shipments.unshift(Object.assign({},s,{currentHumidity:50,batteryLevel:100,riskClassification:"Normal",excursionSeverity:"Safe",estimatedViabilityPercent:99,predictedSpoilageRiskPercent:1,estimatedRemainingViabilityPercent:99}));}
 close();app.renderCurrentView();toast("Shipment "+d.id+" added.","safe");
 }catch(x){err.textContent=x.message||"Save failed.";err.classList.remove("hidden");btn.disabled=false;btn.textContent="Save shipment";}};
}
async function remove(id){if(!confirm("Remove shipment "+id+" from Firebase and the fleet? This cannot be undone."))return;try{var u=user(),database=db();if(!u||u.isDemo||!u.uid||!database)throw Error("Sign in with Firebase to remove database shipments.");await database.ref("shipments/"+id).remove();if(app.simulation)app.simulation.shipments=app.simulation.shipments.filter(function(s){return String(s.id)!==String(id);});breaches.delete(String(id));app.renderCurrentView();toast("Shipment "+id+" removed.","safe");}catch(e){toast("Could not remove shipment: "+e.message,"warning");}}
function send(payload){
 var u=user();if(!u||u.isDemo){toast("Sign in to create an email alert draft.","warning");return;}
 var test=payload.type==="test",subject=test?"ColdGuard email alert test":"ColdGuard temperature excursion: "+(payload.shipmentId||"Unknown shipment");
 var lines=test?["ColdGuard email delivery test","Requested by: "+(u.email||u.uid),"Time: "+new Date().toISOString()]:["A shipment temperature is outside its configured operating range.","Shipment ID: "+payload.shipmentId,"Product: "+(payload.vaccineName||"Unknown"),"Batch: "+(payload.batchNumber||"Not recorded"),"Temperature: "+payload.temperature+" °C","Allowed range: "+payload.minTemp+" °C to "+payload.maxTemp+" °C","Location: "+(payload.location||"Not recorded"),"Destination: "+(payload.destination||"Not recorded"),"Detected at: "+(payload.detectedAt||new Date().toISOString()),"Please verify source telemetry before making product-safety decisions."];
 var body=lines.join("\n");var href="mailto:?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body);
 try{window.location.href=href;toast("Your email app should open with the alert draft. Review it and press Send. No email provider or Vercel environment variables are used.","info");}catch(e){toast("Could not open an email app. Check that a mail app is configured on this device.","warning");}
}
function watch(list){if(!Array.isArray(list))return;var ids=new Set();list.forEach(function(s){var id=String(s.id||s.shipmentId||"");if(!id)return;ids.add(id);var raw=s.telemetry&&s.telemetry.live&&s.telemetry.live.temperature;if(raw==null||raw==="")raw=s.currentTemperature;if(raw==null||raw==="")return;var temp=Number(raw),p=(app.vaccineProfiles||{})[s.vaccineCategory]||{},min=Number(s.minAllowedTemperature!=null?s.minAllowedTemperature:s.minTemp!=null?s.minTemp:p.minTemp),max=Number(s.maxAllowedTemperature!=null?s.maxAllowedTemperature:s.maxTemp!=null?s.maxTemp:p.maxTemp);if(!Number.isFinite(temp)||!Number.isFinite(min)||!Number.isFinite(max)||min>=max)return;var bad=temp<min||temp>max,was=breaches.get(id)===true;breaches.set(id,bad);if(bad&&!was)send({type:"temperature_excursion",shipmentId:id,vaccineName:s.vaccineName||s.productName||"Unknown",batchNumber:s.batchNumber||"Not recorded",temperature:temp,minTemp:min,maxTemp:max,location:s.currentLocation||(s.location&&s.location.name)||"Not recorded",destination:s.destinationFacility||s.destination||"Not recorded",detectedAt:new Date().toISOString()});});Array.from(breaches.keys()).forEach(function(id){if(!ids.has(id))breaches.delete(id);});}
function boot(){app=window.coldGuardApp;if(!app){setTimeout(boot,50);return;}var rv=app.renderShipmentsTableView.bind(app);app.renderShipmentsTableView=function(c){rv(c);controls();};var rt=app.renderShipmentsTable.bind(app);app.renderShipmentsTable=function(){rt();controls();};if(app.dbService&&app.dbService.on)app.dbService.on("shipments",watch);if(app.currentView==="shipments")controls();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(boot,0);});else boot();
})();