(function(){
"use strict";
var app=null, dbUrl="https://coldguard-fdfc5-default-rtdb.asia-southeast1.firebasedatabase.app", breaches=new Map();
var $=function(id){return document.getElementById(id);};
var esc=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]);});};
function user(){return app&&app.currentUser||(window.firebase&&window.firebase.auth?window.firebase.auth().currentUser:null);}
function db(){try{return app&&app.dbService&&app.dbService.db||window.firebase.app().database(dbUrl);}catch(e){return null;}}
function toast(msg,type){if(app&&app.modals&&app.modals.showToast)app.modals.showToast(msg,type||"info");else alert(msg);}
function field(n,l,p,t,req){return '<label class="text-xs font-semibold text-slate-700">'+l+'<input name="'+n+'" type="'+t+'" '+(t==="number"?'step="any" ':'maxlength="100" ')+(req?"required ":"")+' placeholder="'+esc(p)+'" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"></label>';}
function controls(){
 if(!app||app.currentView!=="shipments")return;
 var h=document.querySelector("#main-content-view h1"), header=h&&h.parentElement&&h.parentElement.parentElement;
 if(header){var a=$("cg-actions");if(!a){a=document.createElement("div");a.id="cg-actions";a.className="flex flex-wrap items-center gap-2";header.appendChild(a);}
 a.innerHTML='<button id="cg-contact" class="px-3 py-2 text-xs font-semibold bg-white border border-slate-300 rounded-xl">Emergency contacts</button><button id="cg-test-email" class="px-3 py-2 text-xs font-semibold bg-white border border-slate-300 rounded-xl">Test alert</button><button id="cg-add" class="px-3.5 py-2 text-xs font-bold bg-emerald-600 text-white rounded-xl">+ Add shipment</button>';
 $("cg-add").onclick=addForm;$("cg-contact").onclick=contactForm;$("cg-test-email").onclick=function(){send({type:"test",shipmentId:"ALERT-TEST"});};}
 document.querySelectorAll("#shipments-table-wrapper .shipment-row[data-id]").forEach(function(row){var id=row.getAttribute("data-id"),cell=row.lastElementChild;if(!id||!cell||cell.querySelector(".cg-remove"))return;var b=document.createElement("button");b.className="cg-remove ml-1 px-2.5 py-1.5 text-xs font-semibold text-red-700 bg-red-50 border border-red-200 rounded-lg";b.textContent="Remove";b.onclick=function(e){e.preventDefault();e.stopPropagation();remove(id);};cell.appendChild(b);});
}
function addForm(){
 var modal=$("modal-container"),profiles=app.vaccineProfiles||{};if(!modal)return;
 var opts=Object.keys(profiles).map(function(k){return '<option value="'+esc(k)+'">'+esc(profiles[k].categoryName||k)+'</option>';}).join("");
 modal.innerHTML='<div class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-4"><form id="cg-form" class="w-full max-w-2xl max-h-[92vh] overflow-y-auto bg-white rounded-2xl shadow-2xl p-6 space-y-4"><div class="flex justify-between"><h2 class="text-xl font-extrabold">Add new shipment</h2><button id="cg-close" type="button" class="text-2xl">&times;</button></div><div class="grid grid-cols-1 sm:grid-cols-2 gap-3">'+
 field("id","Shipment ID","CG-IN-NEW-001","text",true)+field("vaccineName","Product / vaccine","Vaccine name","text",true)+
 '<label class="text-xs font-semibold">Category<select name="vaccineCategory" class="mt-1 w-full rounded-lg border p-2.5">'+opts+'</select></label>'+
 field("batchNumber","Batch number","BATCH-001","text",true)+field("minTemp","Minimum temperature (°C)","","number",true)+field("maxTemp","Maximum temperature (°C)","","number",true)+field("currentLocation","Origin","Origin facility","text",true)+field("destinationFacility","Destination","Destination facility","text",true)+field("driverName","Driver name","Optional","text",false)+field("sensorDeviceId","Sensor / device ID","Optional","text",false)+
 '</div><p id="cg-error" class="hidden text-xs text-red-700"></p><div class="flex justify-end gap-2"><button id="cg-cancel" type="button" class="px-4 py-2 border rounded-lg">Cancel</button><button id="cg-save" type="submit" class="px-4 py-2 font-bold text-white bg-emerald-600 rounded-lg">Save shipment</button></div></form></div>';
 var f=$("cg-form"),close=function(){$("modal-container").innerHTML="";};
 $("cg-close").onclick=close;$("cg-cancel").onclick=close;
 function defaults(){var p=profiles[f.elements.vaccineCategory.value]||{};f.elements.minTemp.value=Number.isFinite(Number(p.minTemp))?p.minTemp:2;f.elements.maxTemp.value=Number.isFinite(Number(p.maxTemp))?p.maxTemp:8;}
 f.elements.vaccineCategory.onchange=defaults;defaults();
 f.onsubmit=async function(e){e.preventDefault();var err=$("cg-error"),btn=$("cg-save");err.classList.add("hidden");btn.disabled=true;btn.textContent="Saving…";
 try{var d=Object.fromEntries(new FormData(f).entries()),u=user(),database=db();d.id=d.id.trim();d.minTemp=Number(d.minTemp);d.maxTemp=Number(d.maxTemp);
 if(!/^[A-Za-z0-9_-]{1,64}$/.test(d.id))throw Error("ID may contain only letters, numbers, hyphens and underscores.");
 if(!Number.isFinite(d.minTemp)||!Number.isFinite(d.maxTemp)||d.minTemp>=d.maxTemp)throw Error("Minimum temperature must be lower than maximum temperature.");
 if(!u||u.isDemo||!u.uid||!database)throw Error("Sign in with Firebase to save shipments; demo mode cannot write to the database.");
 var ref=database.ref("shipments/"+d.id);if((await ref.once("value")).exists())throw Error("That shipment ID already exists.");
 var now=new Date().toISOString(),s={id:d.id,shipmentId:d.id,vaccineName:d.vaccineName.trim(),productName:d.vaccineName.trim(),vaccineCategory:d.vaccineCategory,batchNumber:d.batchNumber.trim(),minTemp:d.minTemp,maxTemp:d.maxTemp,minAllowedTemperature:d.minTemp,maxAllowedTemperature:d.maxTemp,currentLocation:d.currentLocation.trim(),origin:d.currentLocation.trim(),destinationFacility:d.destinationFacility.trim(),destination:d.destinationFacility.trim(),driverName:d.driverName.trim(),sensorDeviceId:d.sensorDeviceId.trim(),status:"In Transit",createdAt:now,updatedAt:now,createdByUid:u.uid,currentTemperature:(d.minTemp+d.maxTemp)/2,temperatureUnit:"C"};
 await ref.set(s);if(app.simulation&&Array.isArray(app.simulation.shipments)){app.simulation.shipments=app.simulation.shipments.filter(function(x){return String(x.id)!==d.id;});app.simulation.shipments.unshift(Object.assign({},s,{currentHumidity:50,batteryLevel:100,riskClassification:"Normal",excursionSeverity:"Safe",estimatedViabilityPercent:99,predictedSpoilageRiskPercent:1,estimatedRemainingViabilityPercent:99}));}
 close();app.renderCurrentView();toast("Shipment "+d.id+" added.","safe");
 }catch(x){err.textContent=x.message||"Save failed.";err.classList.remove("hidden");btn.disabled=false;btn.textContent="Save shipment";}};
}
function contactForm(){
 var modal=$("modal-container"),u=user(),database=db();if(!modal)return;
 if(!u||u.isDemo||!u.uid||!database){toast("Sign in with Firebase to configure emergency contacts.","warning");return;}
 modal.innerHTML='<div class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-4"><form id="cg-contact-form" class="w-full max-w-lg bg-white rounded-2xl shadow-2xl p-6 space-y-4"><div class="flex justify-between items-center"><h2 class="text-xl font-extrabold">Emergency contacts</h2><button id="cg-contact-close" type="button" class="text-2xl">&times;</button></div><p class="text-sm text-slate-600">Add the email and/or mobile number that should receive ColdGuard alerts. SMS needs Twilio setup; email needs Brevo setup in Vercel.</p><label class="block text-xs font-semibold">Emergency email<input name="email" type="email" maxlength="254" placeholder="safety@example.com" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"></label><label class="block text-xs font-semibold">Emergency mobile (include country code)<input name="phone" type="tel" maxlength="16" placeholder="+919876543210" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"></label><p id="cg-contact-error" class="hidden text-xs text-red-700"></p><div class="flex justify-end gap-2"><button id="cg-contact-cancel" type="button" class="px-4 py-2 border rounded-lg">Cancel</button><button id="cg-contact-save" type="submit" class="px-4 py-2 font-bold text-white bg-emerald-600 rounded-lg">Save contacts</button></div></form></div>';
 var form=$("cg-contact-form"),close=function(){$("modal-container").innerHTML="";};$("cg-contact-close").onclick=close;$("cg-contact-cancel").onclick=close;
 database.ref("users/"+u.uid+"/emergencyContact").once("value").then(function(s){var v=s.val()||{};form.elements.email.value=v.email||"";form.elements.phone.value=v.phone||"";}).catch(function(){});
 form.onsubmit=async function(e){e.preventDefault();var email=form.elements.email.value.trim(),phone=form.elements.phone.value.trim(),err=$("cg-contact-error"),btn=$("cg-contact-save");err.classList.add("hidden");
 if(!email&&!phone){err.textContent="Enter an emergency email, mobile number, or both.";err.classList.remove("hidden");return;}
 if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){err.textContent="Enter a valid email address.";err.classList.remove("hidden");return;}
 if(phone&&!/^\+[1-9]\d{7,14}$/.test(phone)){err.textContent="Use international format, for example +919876543210.";err.classList.remove("hidden");return;}
 btn.disabled=true;btn.textContent="Saving…";try{await database.ref("users/"+u.uid+"/emergencyContact").set({email:email,phone:phone,updatedAt:new Date().toISOString()});close();toast("Emergency contacts saved.","safe");}
 catch(x){err.textContent="Could not save contacts: "+x.message;err.classList.remove("hidden");btn.disabled=false;btn.textContent="Save contacts";}
 };
}

async function remove(id){if(!confirm("Remove shipment "+id+" from the visible fleet? If signed in, its Firebase record will also be deleted."))return;try{var u=user(),database=db(),remote=!!(u&&!u.isDemo&&u.uid&&database);if(remote)await database.ref("shipments/"+id).remove();if(app.simulation&&Array.isArray(app.simulation.shipments))app.simulation.shipments=app.simulation.shipments.filter(function(s){return String(s.id)!==String(id);});breaches.delete(String(id));app.renderCurrentView();toast(remote?"Shipment "+id+" removed from Firebase and fleet.":"Shipment "+id+" removed from this session only; sign in to delete its Firebase record.","safe");}catch(e){toast("Could not remove shipment: "+e.message,"warning");}}
async function send(payload){var u=user();if(!u||u.isDemo||!u.uid){toast("Sign in with Firebase to send emergency alerts.","warning");return;}try{var token=await u.getIdToken(),r=await fetch("/api/send-alert",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify(payload)}),out=await r.json().catch(function(){return {};});if(!r.ok)throw Error(out.error||"Alert service failed.");toast(out.message||"Emergency alert request completed.","safe");}catch(e){toast("Alert was not sent: "+(e.message||"Check email/SMS provider setup."),"warning");}}
var latestShipmentList=[],hasInitialSnapshot=false;
function watch(list){if(!Array.isArray(list))return;latestShipmentList=list;var isInitialSnapshot=!hasInitialSnapshot;hasInitialSnapshot=true;var active=new Set(),now=Date.now();list.forEach(function(s){var id=String(s.id||s.shipmentId||"");if(!id)return;
 var raw=s.telemetry&&s.telemetry.live&&s.telemetry.live.temperature;if(raw==null||raw==="")raw=s.currentTemperature;
 var p=(app.vaccineProfiles||{})[s.vaccineCategory]||{},min=Number(s.minAllowedTemperature!=null?s.minAllowedTemperature:s.minTemp!=null?s.minTemp:p.minTemp),max=Number(s.maxAllowedTemperature!=null?s.maxAllowedTemperature:s.maxTemp!=null?s.maxTemp:p.maxTemp);
 if(raw!=null&&raw!==""&&Number.isFinite(Number(raw))&&Number.isFinite(min)&&Number.isFinite(max)&&min<max){var temp=Number(raw),key="temp:"+id,bad=temp<min||temp>max,was=breaches.get(key)===true;active.add(key);breaches.set(key,bad);if(bad&&!was&&!isInitialSnapshot)send({type:"temperature_excursion",shipmentId:id,vaccineName:s.vaccineName||s.productName||"Unknown",batchNumber:s.batchNumber||"Not recorded",temperature:temp,minTemp:min,maxTemp:max,location:s.currentLocation||(s.location&&s.location.name)||"Not recorded",destination:s.destinationFacility||s.destination||"Not recorded",detectedAt:new Date().toISOString()});}
 var live=(s.telemetry&&s.telemetry.live)||{},stamp=live.lastSensorUpdate||live.timestamp||live.updatedAt||s.lastSensorUpdate,stampMs=stamp?Date.parse(stamp):NaN;if(!Number.isFinite(stampMs)&&typeof stamp==="number")stampMs=stamp<1000000000000?stamp*1000:stamp;
 var offlineKey="offline:"+id;if(Number.isFinite(stampMs)){var offline=now-stampMs>5*60*1000,wasOffline=breaches.get(offlineKey)===true;active.add(offlineKey);breaches.set(offlineKey,offline);if(offline&&!wasOffline&&!isInitialSnapshot)send({type:"sensor_offline",shipmentId:id,vaccineName:s.vaccineName||s.productName||"Unknown",location:s.currentLocation||(s.location&&s.location.name)||"Not recorded",detectedAt:new Date().toISOString(),lastSensorUpdate:new Date(stampMs).toISOString()});}
 var status=String(s.hardwareStatus||s.deviceStatus||s.sensorStatus||"").toLowerCase(),fault=["fault","error","failed","offline","disconnected","malfunction"].indexOf(status)>=0,hwKey="hardware:"+id,wasFault=breaches.get(hwKey)===true;active.add(hwKey);breaches.set(hwKey,fault);if(fault&&!wasFault&&!isInitialSnapshot)send({type:"hardware_problem",shipmentId:id,vaccineName:s.vaccineName||s.productName||"Unknown",location:s.currentLocation||(s.location&&s.location.name)||"Not recorded",detectedAt:new Date().toISOString(),hardwareStatus:status});
 });Array.from(breaches.keys()).forEach(function(key){var id=key.slice(key.indexOf(":")+1);if(!latestShipmentList.some(function(s){return String(s.id||s.shipmentId||"")===id;}))breaches.delete(key);});}

function boot(){app=window.coldGuardApp;if(!app){setTimeout(boot,50);return;}var rv=app.renderShipmentsTableView.bind(app);app.renderShipmentsTableView=function(c){rv(c);controls();};var rt=app.renderShipmentsTable.bind(app);app.renderShipmentsTable=function(){rt();controls();};if(app.dbService&&app.dbService.on)app.dbService.on("shipments",watch);setInterval(function(){if(latestShipmentList.length)watch(latestShipmentList);},60000);if(app.currentView==="shipments")controls();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(boot,0);});else boot();
})();