function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]);});}
module.exports=async function(req,res){
 res.setHeader("Cache-Control","no-store");
 if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});
 const brevoKey=process.env.BREVO_API_KEY,defaultEmail=process.env.ALERT_EMAIL_TO,from=process.env.ALERT_FROM_EMAIL,webApiKey=process.env.FIREBASE_WEB_API_KEY;
 const twilioSid=process.env.TWILIO_ACCOUNT_SID,twilioToken=process.env.TWILIO_AUTH_TOKEN,twilioFrom=process.env.TWILIO_FROM_NUMBER;
 if(!webApiKey)return res.status(503).json({error:"Missing FIREBASE_WEB_API_KEY in Vercel environment variables."});
 const h=req.headers.authorization||"",token=h.indexOf("Bearer ")===0?h.slice(7):"";
 if(!token)return res.status(401).json({error:"Sign in is required to send emergency alerts."});
 let user;try{const vr=await fetch("https://identitytoolkit.googleapis.com/v1/accounts:lookup?key="+encodeURIComponent(webApiKey),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:token})});const vd=await vr.json().catch(function(){return {};});if(!vr.ok||!vd.users||!vd.users.length)return res.status(401).json({error:"Firebase session is invalid or expired. Sign in again."});user={uid:vd.users[0].localId,email:vd.users[0].email};}catch(e){console.error("ColdGuard auth verification failed",e.message);return res.status(502).json({error:"Could not verify the Firebase session."});}
 const b=req.body||{},test=b.type==="test",id=String(b.shipmentId||"").slice(0,100);
 if(!test&&b.type!=="temperature_excursion")return res.status(400).json({error:"Unsupported alert type."});
 if(!test&&(!id||!Number.isFinite(Number(b.temperature))))return res.status(400).json({error:"Shipment ID and valid temperature are required."});
 const databaseUrl=(process.env.FIREBASE_DATABASE_URL||"https://coldguard-fdfc5-default-rtdb.asia-southeast1.firebasedatabase.app").replace(/\/$/,"");
 let contact={};try{const cr=await fetch(databaseUrl+"/users/"+encodeURIComponent(user.uid)+"/emergencyContact.json?auth="+encodeURIComponent(token));if(cr.ok)contact=(await cr.json())||{};}catch(e){console.warn("Could not read saved emergency contact",e.message);}
 const email=String(contact.email||defaultEmail||"").trim(),phone=String(contact.phone||process.env.ALERT_PHONE_TO||"").trim();
 const rows=test?[["Status","ColdGuard alert delivery test"],["Requested by",user.email||user.uid],["Time",new Date().toISOString()]]:[["Shipment ID",id],["Product",b.vaccineName||"Unknown"],["Batch",b.batchNumber||"Not recorded"],["Temperature",Number(b.temperature)+" °C"],["Allowed range",b.minTemp+" °C to "+b.maxTemp+" °C"],["Location",b.location||"Not recorded"],["Destination",b.destination||"Not recorded"],["Detected at",b.detectedAt||new Date().toISOString()],["Operator",user.email||user.uid]];
 const subject=test?"ColdGuard emergency alert test":"ColdGuard temperature excursion: "+id;
 const html="<div style=\"font-family:Arial,sans-serif;color:#0f172a\"><h2 style=\"color:"+(test?"#047857":"#b91c1c")+"\">"+(test?"ColdGuard alert test":"Temperature excursion detected")+"</h2><p>"+(test?"This is a test of the configured emergency channels.":"A shipment temperature is outside its configured operating range. Follow your cold-chain escalation procedure.")+"</p><table style=\"border-collapse:collapse;width:100%\">"+rows.map(function(r){return "<tr><th style=\"text-align:left;padding:9px;border:1px solid #e2e8f0;background:#f8fafc\">"+esc(r[0])+"</th><td style=\"padding:9px;border:1px solid #e2e8f0\">"+esc(r[1])+"</td></tr>";}).join("")+"</table><p style=\"font-size:12px;color:#64748b\">Verify source telemetry before making product-safety decisions.</p></div>";
 const sms=(test?"ColdGuard alert test. ":"COLDGUARD ALERT: Temperature excursion. ")+"Shipment "+(id||"test")+". "+(test?"Verify configured alert delivery.":"Temperature "+Number(b.temperature)+" C; allowed "+b.minTemp+" to "+b.maxTemp+" C. Location: "+(b.location||"Not recorded")+".");
 const results=[],errors=[];
 if(email&&brevoKey&&from){try{const er=await fetch("https://api.brevo.com/v3/smtp/email",{method:"POST",headers:{"api-key":brevoKey,"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({sender:{name:"ColdGuard Alerts",email:from},to:[{email:email}],subject:subject,htmlContent:html})});const eo=await er.json().catch(function(){return {};});if(!er.ok)throw Error(eo.message||"Brevo rejected the email.");results.push("email");}catch(e){console.error("ColdGuard email delivery failed",e.message);errors.push("Email: "+e.message);}}
 else if(email)errors.push("Email is saved, but configure BREVO_API_KEY and ALERT_FROM_EMAIL in Vercel.");
 if(phone&&twilioSid&&twilioToken&&twilioFrom){try{const form=new URLSearchParams({To:phone,From:twilioFrom,Body:sms});const sr=await fetch("https://api.twilio.com/2010-04-01/Accounts/"+encodeURIComponent(twilioSid)+"/Messages.json",{method:"POST",headers:{"Authorization":"Basic "+Buffer.from(twilioSid+":"+twilioToken).toString("base64"),"Content-Type":"application/x-www-form-urlencoded"},body:form.toString()});const so=await sr.json().catch(function(){return {};});if(!sr.ok)throw Error(so.message||"Twilio rejected the SMS.");results.push("SMS");}catch(e){console.error("ColdGuard SMS delivery failed",e.message);errors.push("SMS: "+e.message);}}
 else if(phone)errors.push("Mobile number is saved, but configure TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN and TWILIO_FROM_NUMBER in Vercel.");
 if(!email&&!phone)return res.status(400).json({error:"No emergency recipient configured. Open Shipment Fleet → Emergency contacts and add an email or mobile number."});
 if(!results.length)return res.status(503).json({error:errors.join(" ")||"No alert channel is configured. Add provider credentials in Vercel."});
 return res.status(200).json({ok:true,channels:results,message:"Alert accepted for "+results.join(" and ")+(errors.length?"; "+errors.join(" "):".")});
};